#include "setstyle.C"

#include "TH1F.h"

#include "TPaveText.h"

#include "TLegend.h"

#include "TCanvas.h"

#include "THStack.h"

#include <string>

#include <iostream>

class shapePlotter{
 
public:
void plotS0B0D0( );
void plotS0B0D1( string VarName,TPaveText *txtGen , TH1F *hd, string proc_data);
void plotS0B1D0( string VarName,TPaveText *txtGen ,  TH1F *hb1  , string bkg_proc1 );
void plotS0B1D1( string VarName,TPaveText *txtGen , TH1F *hb1,  string bkg_proc1,  TH1F *hd, string proc_data);
void plotS0B2D0( string VarName,TPaveText *txtGen ,  TH1F *hb1  , string bkg_proc1 ,  TH1F *hb2  , string bkg_proc2 );
void plotS0B2D1( string VarName,TPaveText *txtGen , TH1F *hb1,  string bkg_proc1,  TH1F *hb2,  string bkg_proc2,  TH1F *hd, string proc_data);
void plotS0B3D0( string VarName,TPaveText *txtGen ,  TH1F *hb1  , string bkg_proc1 ,  TH1F *hb2  , string bkg_proc2 ,  TH1F *hb3  , string bkg_proc3 );
void plotS0B3D1( string VarName,TPaveText *txtGen , TH1F *hb1,  string bkg_proc1,  TH1F *hb2,  string bkg_proc2,  TH1F *hb3,  string bkg_proc3,  TH1F *hd, string proc_data);
void plotS0B4D0( string VarName,TPaveText *txtGen ,  TH1F *hb1  , string bkg_proc1 ,  TH1F *hb2  , string bkg_proc2 ,  TH1F *hb3  , string bkg_proc3 ,  TH1F *hb4  , string bkg_proc4 );
void plotS0B4D1( string VarName,TPaveText *txtGen , TH1F *hb1,  string bkg_proc1,  TH1F *hb2,  string bkg_proc2,  TH1F *hb3,  string bkg_proc3,  TH1F *hb4,  string bkg_proc4,  TH1F *hd, string proc_data);
void plotS1B0D0( string VarName,TPaveText *txtGen , TH1F *hs1 , string sig_proc1 );
void plotS1B0D1( string VarName,TPaveText *txtGen , TH1F *hs1,  string sig_proc1,  TH1F *hd, string proc_data);
void plotS1B1D0( string VarName,TPaveText *txtGen , TH1F *hs1 , string sig_proc1 ,  TH1F *hb1  , string bkg_proc1 );
void plotS1B1D1( string VarName,TPaveText *txtGen , TH1F *hs1,  string sig_proc1,  TH1F *hb1,  string bkg_proc1,  TH1F *hd, string proc_data);
void plotS1B2D0( string VarName,TPaveText *txtGen , TH1F *hs1 , string sig_proc1 ,  TH1F *hb1  , string bkg_proc1 ,  TH1F *hb2  , string bkg_proc2 );
void plotS1B2D1( string VarName,TPaveText *txtGen , TH1F *hs1,  string sig_proc1,  TH1F *hb1,  string bkg_proc1,  TH1F *hb2,  string bkg_proc2,  TH1F *hd, string proc_data);
void plotS1B3D0( string VarName,TPaveText *txtGen , TH1F *hs1 , string sig_proc1 ,  TH1F *hb1  , string bkg_proc1 ,  TH1F *hb2  , string bkg_proc2 ,  TH1F *hb3  , string bkg_proc3 );
void plotS1B3D1( string VarName,TPaveText *txtGen , TH1F *hs1,  string sig_proc1,  TH1F *hb1,  string bkg_proc1,  TH1F *hb2,  string bkg_proc2,  TH1F *hb3,  string bkg_proc3,  TH1F *hd, string proc_data);
void plotS1B4D0( string VarName,TPaveText *txtGen , TH1F *hs1 , string sig_proc1 ,  TH1F *hb1  , string bkg_proc1 ,  TH1F *hb2  , string bkg_proc2 ,  TH1F *hb3  , string bkg_proc3 ,  TH1F *hb4  , string bkg_proc4 );
void plotS1B4D1( string VarName,TPaveText *txtGen , TH1F *hs1,  string sig_proc1,  TH1F *hb1,  string bkg_proc1,  TH1F *hb2,  string bkg_proc2,  TH1F *hb3,  string bkg_proc3,  TH1F *hb4,  string bkg_proc4,  TH1F *hd, string proc_data);
void plotS2B0D0( string VarName,TPaveText *txtGen , TH1F *hs1 , string sig_proc1 , TH1F *hs2 , string sig_proc2 );
void plotS2B0D1( string VarName,TPaveText *txtGen , TH1F *hs1,  string sig_proc1,  TH1F *hs2,  string sig_proc2,  TH1F *hd, string proc_data);
void plotS2B1D0( string VarName,TPaveText *txtGen , TH1F *hs1 , string sig_proc1 , TH1F *hs2 , string sig_proc2 ,  TH1F *hb1  , string bkg_proc1 );
void plotS2B1D1( string VarName,TPaveText *txtGen , TH1F *hs1,  string sig_proc1,  TH1F *hs2,  string sig_proc2,  TH1F *hb1,  string bkg_proc1,  TH1F *hd, string proc_data);
void plotS2B2D0( string VarName,TPaveText *txtGen , TH1F *hs1 , string sig_proc1 , TH1F *hs2 , string sig_proc2 ,  TH1F *hb1  , string bkg_proc1 ,  TH1F *hb2  , string bkg_proc2 );
void plotS2B2D1( string VarName,TPaveText *txtGen , TH1F *hs1,  string sig_proc1,  TH1F *hs2,  string sig_proc2,  TH1F *hb1,  string bkg_proc1,  TH1F *hb2,  string bkg_proc2,  TH1F *hd, string proc_data);
void plotS2B3D0( string VarName,TPaveText *txtGen , TH1F *hs1 , string sig_proc1 , TH1F *hs2 , string sig_proc2 ,  TH1F *hb1  , string bkg_proc1 ,  TH1F *hb2  , string bkg_proc2 ,  TH1F *hb3  , string bkg_proc3 );
void plotS2B3D1( string VarName,TPaveText *txtGen , TH1F *hs1,  string sig_proc1,  TH1F *hs2,  string sig_proc2,  TH1F *hb1,  string bkg_proc1,  TH1F *hb2,  string bkg_proc2,  TH1F *hb3,  string bkg_proc3,  TH1F *hd, string proc_data);
void plotS2B4D0( string VarName,TPaveText *txtGen , TH1F *hs1 , string sig_proc1 , TH1F *hs2 , string sig_proc2 ,  TH1F *hb1  , string bkg_proc1 ,  TH1F *hb2  , string bkg_proc2 ,  TH1F *hb3  , string bkg_proc3 ,  TH1F *hb4  , string bkg_proc4 );
void plotS2B4D1( string VarName,TPaveText *txtGen , TH1F *hs1,  string sig_proc1,  TH1F *hs2,  string sig_proc2,  TH1F *hb1,  string bkg_proc1,  TH1F *hb2,  string bkg_proc2,  TH1F *hb3,  string bkg_proc3,  TH1F *hb4,  string bkg_proc4,  TH1F *hd, string proc_data);
};
void shapePlotter::plotS0B0D0( ){
using namespace std;
TStyle *gStyle = new TStyle("gStyle","Style for P-TDR");
setStyle st;
st.SetPars(gStyle);
TPaveText *pCMS = new TPaveText(0.132107,0.9308003,0.8327759,0.9923583,"brNDC");
pCMS->SetBorderSize(0);
pCMS->SetFillStyle(0);
pCMS->SetTextAlign(11);
pCMS->SetTextFont(42);
pCMS->SetTextSize(0.04);
pCMS->AddText("CMS Phase 2 #it{Preliminary}                    ");
TLegend *leg=new TLegend(0.3582943,0.7051483,0.55025753,0.9049564,NULL,"brNDC");
leg->SetTextFont(62);
leg->SetLineColor(1);
leg->SetLineStyle(1);
leg->SetLineWidth(3);
leg->SetFillColor(0);
leg->SetFillStyle(1001);
leg->SetShadowColor(0);
leg->SetDrawOption(0);
leg->SetBorderSize(0);
leg->SetTextSize(0.03);
THStack *hallbkg=new THStack("hallbkg","a;x;y");
TCanvas *c=new TCanvas("c","c");
c->cd();
pCMS->Draw();
leg->Draw();
c->Write();
}

void shapePlotter::plotS0B0D1( string VarName,TPaveText *txtGen , TH1F *hd, string proc_data){
using namespace std;
TStyle *gStyle = new TStyle("gStyle","Style for P-TDR");
setStyle st;
st.SetPars(gStyle);
TPaveText *pCMS = new TPaveText(0.132107,0.9308003,0.8327759,0.9923583,"brNDC");
pCMS->SetBorderSize(0);
pCMS->SetFillStyle(0);
pCMS->SetTextAlign(11);
pCMS->SetTextFont(42);
pCMS->SetTextSize(0.04);
pCMS->AddText("CMS Phase 2 #it{Preliminary}                   ");
TLegend *leg=new TLegend(0.3582943,0.7051483,0.55025753,0.9049564,NULL,"brNDC");
leg->SetTextFont(62);
leg->SetLineColor(1);
leg->SetLineStyle(1);
leg->SetLineWidth(3);
leg->SetFillColor(0);
leg->SetFillStyle(1001);
leg->SetShadowColor(0);
leg->SetDrawOption(0);
leg->SetBorderSize(0);
leg->SetTextSize(0.03);
char Variable[100];
char Cname[100];
const char *Var_Name;
Var_Name=VarName.c_str();
sprintf(Variable," ;%s;Events",Var_Name);
sprintf(Cname,"%s",Var_Name);
THStack *hallbkg=new THStack("hallbkg",Variable);
hd->SetLineColor(1);
hd->SetMarkerStyle(20);
char hL_data[100];
const char *h_L_data;
h_L_sig=proc_data.c_str();
sprintf(hL_data,"%s",h_L_sig);
leg->AddEntry(hd,hL_data,"p");
TCanvas *c=new TCanvas(Cname,Cname);
c->cd();
hd->Draw("P,E1 SAME");
txtGen->Draw();
pCMS->Draw();
leg->Draw();
c->Write();
}

void shapePlotter::plotS0B1D0( string VarName,TPaveText *txtGen ,  TH1F *hb1  , string bkg_proc1 ){
using namespace std;
TStyle *gStyle = new TStyle("gStyle","Style for P-TDR");
setStyle st;
st.SetPars(gStyle);
char Variable[100];
char Cname[100];
const char *Var_Name;
Var_Name=VarName.c_str();
sprintf(Variable," ;%s; Events",Var_Name);
sprintf(Cname,"%s",Var_Name);
TPaveText *pCMS = new TPaveText(0.132107,0.9308003,0.8327759,0.9923583,"brNDC");
pCMS->SetBorderSize(0);
pCMS->SetFillStyle(0);
pCMS->SetTextAlign(11);
pCMS->SetTextFont(42);
pCMS->SetTextSize(0.04);
pCMS->AddText("CMS Phase 2 #it{Preliminary}                    ");
TLegend *leg=new TLegend(0.3582943,0.7051483,0.55025753,0.9049564,NULL,"brNDC");
leg->SetTextFont(62);
leg->SetLineColor(1);
leg->SetLineStyle(1);
leg->SetLineWidth(3);
leg->SetFillColor(0);
leg->SetFillStyle(1001);
leg->SetShadowColor(0);
leg->SetDrawOption(0);
leg->SetBorderSize(0);
leg->SetTextSize(0.03);
THStack *hallbkg=new THStack("hallbkg",Variable);
hb1->SetLineColor(1);
hallbkg->Add(hb1);
char h1L_bkg[100];
const char *h1_L_bkg;
h1_L_bkg=bkg_proc1.c_str();
sprintf(h1L_bkg,"%s",h1_L_bkg);
leg->AddEntry(hb1,h1L_bkg,"l");
TCanvas *c=new TCanvas(Cname,Cname);
c->cd();
hb1->Scale(1/hb1->Integral());
hb1->Draw("same");
txtGen->Draw();
pCMS->Draw();
leg->Draw();
c->Write();
}

void shapePlotter::plotS0B1D1( string VarName,TPaveText *txtGen , TH1F *hb1,  string bkg_proc1, 
TH1F *hd, string proc_data){
using namespace std;
TStyle *gStyle = new TStyle("gStyle","Style for P-TDR");
setStyle st;
st.SetPars(gStyle);
TPaveText *pCMS = new TPaveText(0.132107,0.9308003,0.8327759,0.9923583,"brNDC");
pCMS->SetBorderSize(0);
pCMS->SetFillStyle(0);
pCMS->SetTextAlign(11);
pCMS->SetTextFont(42);
pCMS->SetTextSize(0.04);
pCMS->AddText("CMS Phase 2 #it{Preliminary}                   ");
TLegend *leg=new TLegend(0.3582943,0.7051483,0.55025753,0.9049564,NULL,"brNDC");
leg->SetTextFont(62);
leg->SetLineColor(1);
leg->SetLineStyle(1);
leg->SetLineWidth(3);
leg->SetFillColor(0);
leg->SetFillStyle(1001);
leg->SetShadowColor(0);
leg->SetDrawOption(0);
leg->SetBorderSize(0);
leg->SetTextSize(0.03);
char Variable[100];
char Cname[100];
const char *Var_Name;
Var_Name=VarName.c_str();
sprintf(Variable," ;%s;Events",Var_Name);
sprintf(Cname,"%s",Var_Name);
THStack *hallbkg=new THStack("hallbkg",Variable);
hb1->SetLineColor(1);
hallbkg->Add(hb1);
char h1L_bkg[100];
const char *h1_L_bkg;
h1_L_bkg=bkg_proc1.c_str();
sprintf(h1L_bkg,"%s",h1_L_bkg);
leg->AddEntry(hb1,h1L_bkg,"l");
hd->SetLineColor(1);
hd->SetMarkerStyle(20);
char hL_data[100];
const char *h_L_data;
h_L_sig=proc_data.c_str();
sprintf(hL_data,"%s",h_L_sig);
leg->AddEntry(hd,hL_data,"p");
TCanvas *c=new TCanvas(Cname,Cname);
c->cd();
hb1->Scale(1/hb1->Integral());
hb1->Draw("same");
hd->Draw("P,E1 SAME");
txtGen->Draw();
pCMS->Draw();
leg->Draw();
c->Write();
}

void shapePlotter::plotS0B2D0( string VarName,TPaveText *txtGen ,  TH1F *hb1  , string bkg_proc1 ,  TH1F *hb2  , string bkg_proc2 ){
using namespace std;
TStyle *gStyle = new TStyle("gStyle","Style for P-TDR");
setStyle st;
st.SetPars(gStyle);
char Variable[100];
char Cname[100];
const char *Var_Name;
Var_Name=VarName.c_str();
sprintf(Variable," ;%s; Events",Var_Name);
sprintf(Cname,"%s",Var_Name);
TPaveText *pCMS = new TPaveText(0.132107,0.9308003,0.8327759,0.9923583,"brNDC");
pCMS->SetBorderSize(0);
pCMS->SetFillStyle(0);
pCMS->SetTextAlign(11);
pCMS->SetTextFont(42);
pCMS->SetTextSize(0.04);
pCMS->AddText("CMS Phase 2 #it{Preliminary}                    ");
TLegend *leg=new TLegend(0.3582943,0.7051483,0.55025753,0.9049564,NULL,"brNDC");
leg->SetTextFont(62);
leg->SetLineColor(1);
leg->SetLineStyle(1);
leg->SetLineWidth(3);
leg->SetFillColor(0);
leg->SetFillStyle(1001);
leg->SetShadowColor(0);
leg->SetDrawOption(0);
leg->SetBorderSize(0);
leg->SetTextSize(0.03);
THStack *hallbkg=new THStack("hallbkg",Variable);
hb1->SetLineColor(1);
hallbkg->Add(hb1);
char h1L_bkg[100];
const char *h1_L_bkg;
h1_L_bkg=bkg_proc1.c_str();
sprintf(h1L_bkg,"%s",h1_L_bkg);
leg->AddEntry(hb1,h1L_bkg,"l");
hb2->SetLineColor(2);
hallbkg->Add(hb2);
char h2L_bkg[100];
const char *h2_L_bkg;
h2_L_bkg=bkg_proc2.c_str();
sprintf(h2L_bkg,"%s",h2_L_bkg);
leg->AddEntry(hb2,h2L_bkg,"l");
TCanvas *c=new TCanvas(Cname,Cname);
c->cd();
hb1->Scale(1/hb1->Integral());
hb1->Draw("same");
hb2->Scale(1/hb2->Integral());
hb2->Draw("same");
txtGen->Draw();
pCMS->Draw();
leg->Draw();
c->Write();
}

void shapePlotter::plotS0B2D1( string VarName,TPaveText *txtGen , TH1F *hb1,  string bkg_proc1, 
TH1F *hb2,  string bkg_proc2, 
TH1F *hd, string proc_data){
using namespace std;
TStyle *gStyle = new TStyle("gStyle","Style for P-TDR");
setStyle st;
st.SetPars(gStyle);
TPaveText *pCMS = new TPaveText(0.132107,0.9308003,0.8327759,0.9923583,"brNDC");
pCMS->SetBorderSize(0);
pCMS->SetFillStyle(0);
pCMS->SetTextAlign(11);
pCMS->SetTextFont(42);
pCMS->SetTextSize(0.04);
pCMS->AddText("CMS Phase 2 #it{Preliminary}                   ");
TLegend *leg=new TLegend(0.3582943,0.7051483,0.55025753,0.9049564,NULL,"brNDC");
leg->SetTextFont(62);
leg->SetLineColor(1);
leg->SetLineStyle(1);
leg->SetLineWidth(3);
leg->SetFillColor(0);
leg->SetFillStyle(1001);
leg->SetShadowColor(0);
leg->SetDrawOption(0);
leg->SetBorderSize(0);
leg->SetTextSize(0.03);
char Variable[100];
char Cname[100];
const char *Var_Name;
Var_Name=VarName.c_str();
sprintf(Variable," ;%s;Events",Var_Name);
sprintf(Cname,"%s",Var_Name);
THStack *hallbkg=new THStack("hallbkg",Variable);
hb1->SetLineColor(1);
hallbkg->Add(hb1);
char h1L_bkg[100];
const char *h1_L_bkg;
h1_L_bkg=bkg_proc1.c_str();
sprintf(h1L_bkg,"%s",h1_L_bkg);
leg->AddEntry(hb1,h1L_bkg,"l");
hb2->SetLineColor(2);
hallbkg->Add(hb2);
char h2L_bkg[100];
const char *h2_L_bkg;
h2_L_bkg=bkg_proc2.c_str();
sprintf(h2L_bkg,"%s",h2_L_bkg);
leg->AddEntry(hb2,h2L_bkg,"l");
hd->SetLineColor(1);
hd->SetMarkerStyle(20);
char hL_data[100];
const char *h_L_data;
h_L_sig=proc_data.c_str();
sprintf(hL_data,"%s",h_L_sig);
leg->AddEntry(hd,hL_data,"p");
TCanvas *c=new TCanvas(Cname,Cname);
c->cd();
hb1->Scale(1/hb1->Integral());
hb1->Draw("same");
hb2->Scale(1/hb2->Integral());
hb2->Draw("same");
hd->Draw("P,E1 SAME");
txtGen->Draw();
pCMS->Draw();
leg->Draw();
c->Write();
}

void shapePlotter::plotS0B3D0( string VarName,TPaveText *txtGen ,  TH1F *hb1  , string bkg_proc1 ,  TH1F *hb2  , string bkg_proc2 ,  TH1F *hb3  , string bkg_proc3 ){
using namespace std;
TStyle *gStyle = new TStyle("gStyle","Style for P-TDR");
setStyle st;
st.SetPars(gStyle);
char Variable[100];
char Cname[100];
const char *Var_Name;
Var_Name=VarName.c_str();
sprintf(Variable," ;%s; Events",Var_Name);
sprintf(Cname,"%s",Var_Name);
TPaveText *pCMS = new TPaveText(0.132107,0.9308003,0.8327759,0.9923583,"brNDC");
pCMS->SetBorderSize(0);
pCMS->SetFillStyle(0);
pCMS->SetTextAlign(11);
pCMS->SetTextFont(42);
pCMS->SetTextSize(0.04);
pCMS->AddText("CMS Phase 2 #it{Preliminary}                    ");
TLegend *leg=new TLegend(0.3582943,0.7051483,0.55025753,0.9049564,NULL,"brNDC");
leg->SetTextFont(62);
leg->SetLineColor(1);
leg->SetLineStyle(1);
leg->SetLineWidth(3);
leg->SetFillColor(0);
leg->SetFillStyle(1001);
leg->SetShadowColor(0);
leg->SetDrawOption(0);
leg->SetBorderSize(0);
leg->SetTextSize(0.03);
THStack *hallbkg=new THStack("hallbkg",Variable);
hb1->SetLineColor(1);
hallbkg->Add(hb1);
char h1L_bkg[100];
const char *h1_L_bkg;
h1_L_bkg=bkg_proc1.c_str();
sprintf(h1L_bkg,"%s",h1_L_bkg);
leg->AddEntry(hb1,h1L_bkg,"l");
hb2->SetLineColor(2);
hallbkg->Add(hb2);
char h2L_bkg[100];
const char *h2_L_bkg;
h2_L_bkg=bkg_proc2.c_str();
sprintf(h2L_bkg,"%s",h2_L_bkg);
leg->AddEntry(hb2,h2L_bkg,"l");
hb3->SetLineColor(3);
hallbkg->Add(hb3);
char h3L_bkg[100];
const char *h3_L_bkg;
h3_L_bkg=bkg_proc3.c_str();
sprintf(h3L_bkg,"%s",h3_L_bkg);
leg->AddEntry(hb3,h3L_bkg,"l");
TCanvas *c=new TCanvas(Cname,Cname);
c->cd();
hb1->Scale(1/hb1->Integral());
hb1->Draw("same");
hb2->Scale(1/hb2->Integral());
hb2->Draw("same");
hb3->Scale(1/hb3->Integral());
hb3->Draw("same");
txtGen->Draw();
pCMS->Draw();
leg->Draw();
c->Write();
}

void shapePlotter::plotS0B3D1( string VarName,TPaveText *txtGen , TH1F *hb1,  string bkg_proc1, 
TH1F *hb2,  string bkg_proc2, 
TH1F *hb3,  string bkg_proc3, 
TH1F *hd, string proc_data){
using namespace std;
TStyle *gStyle = new TStyle("gStyle","Style for P-TDR");
setStyle st;
st.SetPars(gStyle);
TPaveText *pCMS = new TPaveText(0.132107,0.9308003,0.8327759,0.9923583,"brNDC");
pCMS->SetBorderSize(0);
pCMS->SetFillStyle(0);
pCMS->SetTextAlign(11);
pCMS->SetTextFont(42);
pCMS->SetTextSize(0.04);
pCMS->AddText("CMS Phase 2 #it{Preliminary}                   ");
TLegend *leg=new TLegend(0.3582943,0.7051483,0.55025753,0.9049564,NULL,"brNDC");
leg->SetTextFont(62);
leg->SetLineColor(1);
leg->SetLineStyle(1);
leg->SetLineWidth(3);
leg->SetFillColor(0);
leg->SetFillStyle(1001);
leg->SetShadowColor(0);
leg->SetDrawOption(0);
leg->SetBorderSize(0);
leg->SetTextSize(0.03);
char Variable[100];
char Cname[100];
const char *Var_Name;
Var_Name=VarName.c_str();
sprintf(Variable," ;%s;Events",Var_Name);
sprintf(Cname,"%s",Var_Name);
THStack *hallbkg=new THStack("hallbkg",Variable);
hb1->SetLineColor(1);
hallbkg->Add(hb1);
char h1L_bkg[100];
const char *h1_L_bkg;
h1_L_bkg=bkg_proc1.c_str();
sprintf(h1L_bkg,"%s",h1_L_bkg);
leg->AddEntry(hb1,h1L_bkg,"l");
hb2->SetLineColor(2);
hallbkg->Add(hb2);
char h2L_bkg[100];
const char *h2_L_bkg;
h2_L_bkg=bkg_proc2.c_str();
sprintf(h2L_bkg,"%s",h2_L_bkg);
leg->AddEntry(hb2,h2L_bkg,"l");
hb3->SetLineColor(3);
hallbkg->Add(hb3);
char h3L_bkg[100];
const char *h3_L_bkg;
h3_L_bkg=bkg_proc3.c_str();
sprintf(h3L_bkg,"%s",h3_L_bkg);
leg->AddEntry(hb3,h3L_bkg,"l");
hd->SetLineColor(1);
hd->SetMarkerStyle(20);
char hL_data[100];
const char *h_L_data;
h_L_sig=proc_data.c_str();
sprintf(hL_data,"%s",h_L_sig);
leg->AddEntry(hd,hL_data,"p");
TCanvas *c=new TCanvas(Cname,Cname);
c->cd();
hb1->Scale(1/hb1->Integral());
hb1->Draw("same");
hb2->Scale(1/hb2->Integral());
hb2->Draw("same");
hb3->Scale(1/hb3->Integral());
hb3->Draw("same");
hd->Draw("P,E1 SAME");
txtGen->Draw();
pCMS->Draw();
leg->Draw();
c->Write();
}

void shapePlotter::plotS0B4D0( string VarName,TPaveText *txtGen ,  TH1F *hb1  , string bkg_proc1 ,  TH1F *hb2  , string bkg_proc2 ,  TH1F *hb3  , string bkg_proc3 ,  TH1F *hb4  , string bkg_proc4 ){
using namespace std;
TStyle *gStyle = new TStyle("gStyle","Style for P-TDR");
setStyle st;
st.SetPars(gStyle);
char Variable[100];
char Cname[100];
const char *Var_Name;
Var_Name=VarName.c_str();
sprintf(Variable," ;%s; Events",Var_Name);
sprintf(Cname,"%s",Var_Name);
TPaveText *pCMS = new TPaveText(0.132107,0.9308003,0.8327759,0.9923583,"brNDC");
pCMS->SetBorderSize(0);
pCMS->SetFillStyle(0);
pCMS->SetTextAlign(11);
pCMS->SetTextFont(42);
pCMS->SetTextSize(0.04);
pCMS->AddText("CMS Phase 2 #it{Preliminary}                    ");
TLegend *leg=new TLegend(0.3582943,0.7051483,0.55025753,0.9049564,NULL,"brNDC");
leg->SetTextFont(62);
leg->SetLineColor(1);
leg->SetLineStyle(1);
leg->SetLineWidth(3);
leg->SetFillColor(0);
leg->SetFillStyle(1001);
leg->SetShadowColor(0);
leg->SetDrawOption(0);
leg->SetBorderSize(0);
leg->SetTextSize(0.03);
THStack *hallbkg=new THStack("hallbkg",Variable);
hb1->SetLineColor(1);
hallbkg->Add(hb1);
char h1L_bkg[100];
const char *h1_L_bkg;
h1_L_bkg=bkg_proc1.c_str();
sprintf(h1L_bkg,"%s",h1_L_bkg);
leg->AddEntry(hb1,h1L_bkg,"l");
hb2->SetLineColor(2);
hallbkg->Add(hb2);
char h2L_bkg[100];
const char *h2_L_bkg;
h2_L_bkg=bkg_proc2.c_str();
sprintf(h2L_bkg,"%s",h2_L_bkg);
leg->AddEntry(hb2,h2L_bkg,"l");
hb3->SetLineColor(3);
hallbkg->Add(hb3);
char h3L_bkg[100];
const char *h3_L_bkg;
h3_L_bkg=bkg_proc3.c_str();
sprintf(h3L_bkg,"%s",h3_L_bkg);
leg->AddEntry(hb3,h3L_bkg,"l");
hb4->SetLineColor(4);
hallbkg->Add(hb4);
char h4L_bkg[100];
const char *h4_L_bkg;
h4_L_bkg=bkg_proc4.c_str();
sprintf(h4L_bkg,"%s",h4_L_bkg);
leg->AddEntry(hb4,h4L_bkg,"l");
TCanvas *c=new TCanvas(Cname,Cname);
c->cd();
hb1->Scale(1/hb1->Integral());
hb1->Draw("same");
hb2->Scale(1/hb2->Integral());
hb2->Draw("same");
hb3->Scale(1/hb3->Integral());
hb3->Draw("same");
hb4->Scale(1/hb4->Integral());
hb4->Draw("same");
txtGen->Draw();
pCMS->Draw();
leg->Draw();
c->Write();
}

void shapePlotter::plotS0B4D1( string VarName,TPaveText *txtGen , TH1F *hb1,  string bkg_proc1, 
TH1F *hb2,  string bkg_proc2, 
TH1F *hb3,  string bkg_proc3, 
TH1F *hb4,  string bkg_proc4, 
TH1F *hd, string proc_data){
using namespace std;
TStyle *gStyle = new TStyle("gStyle","Style for P-TDR");
setStyle st;
st.SetPars(gStyle);
TPaveText *pCMS = new TPaveText(0.132107,0.9308003,0.8327759,0.9923583,"brNDC");
pCMS->SetBorderSize(0);
pCMS->SetFillStyle(0);
pCMS->SetTextAlign(11);
pCMS->SetTextFont(42);
pCMS->SetTextSize(0.04);
pCMS->AddText("CMS Phase 2 #it{Preliminary}                   ");
TLegend *leg=new TLegend(0.3582943,0.7051483,0.55025753,0.9049564,NULL,"brNDC");
leg->SetTextFont(62);
leg->SetLineColor(1);
leg->SetLineStyle(1);
leg->SetLineWidth(3);
leg->SetFillColor(0);
leg->SetFillStyle(1001);
leg->SetShadowColor(0);
leg->SetDrawOption(0);
leg->SetBorderSize(0);
leg->SetTextSize(0.03);
char Variable[100];
char Cname[100];
const char *Var_Name;
Var_Name=VarName.c_str();
sprintf(Variable," ;%s;Events",Var_Name);
sprintf(Cname,"%s",Var_Name);
THStack *hallbkg=new THStack("hallbkg",Variable);
hb1->SetLineColor(1);
hallbkg->Add(hb1);
char h1L_bkg[100];
const char *h1_L_bkg;
h1_L_bkg=bkg_proc1.c_str();
sprintf(h1L_bkg,"%s",h1_L_bkg);
leg->AddEntry(hb1,h1L_bkg,"l");
hb2->SetLineColor(2);
hallbkg->Add(hb2);
char h2L_bkg[100];
const char *h2_L_bkg;
h2_L_bkg=bkg_proc2.c_str();
sprintf(h2L_bkg,"%s",h2_L_bkg);
leg->AddEntry(hb2,h2L_bkg,"l");
hb3->SetLineColor(3);
hallbkg->Add(hb3);
char h3L_bkg[100];
const char *h3_L_bkg;
h3_L_bkg=bkg_proc3.c_str();
sprintf(h3L_bkg,"%s",h3_L_bkg);
leg->AddEntry(hb3,h3L_bkg,"l");
hb4->SetLineColor(4);
hallbkg->Add(hb4);
char h4L_bkg[100];
const char *h4_L_bkg;
h4_L_bkg=bkg_proc4.c_str();
sprintf(h4L_bkg,"%s",h4_L_bkg);
leg->AddEntry(hb4,h4L_bkg,"l");
hd->SetLineColor(1);
hd->SetMarkerStyle(20);
char hL_data[100];
const char *h_L_data;
h_L_sig=proc_data.c_str();
sprintf(hL_data,"%s",h_L_sig);
leg->AddEntry(hd,hL_data,"p");
TCanvas *c=new TCanvas(Cname,Cname);
c->cd();
hb1->Scale(1/hb1->Integral());
hb1->Draw("same");
hb2->Scale(1/hb2->Integral());
hb2->Draw("same");
hb3->Scale(1/hb3->Integral());
hb3->Draw("same");
hb4->Scale(1/hb4->Integral());
hb4->Draw("same");
hd->Draw("P,E1 SAME");
txtGen->Draw();
pCMS->Draw();
leg->Draw();
c->Write();
}

void shapePlotter::plotS1B0D0( string VarName,TPaveText *txtGen , TH1F *hs1 , string sig_proc1
){
using namespace std;
TStyle *gStyle = new TStyle("gStyle","Style for P-TDR");
setStyle st;
st.SetPars(gStyle);
char Variable[100];
char Cname[100];
const char *Var_Name;
Var_Name=VarName.c_str();
sprintf(Variable," ;%s; Events",Var_Name);
sprintf(Cname,"%s",Var_Name);
TPaveText *pCMS = new TPaveText(0.132107,0.9308003,0.8327759,0.9923583,"brNDC");
pCMS->SetBorderSize(0);
pCMS->SetFillStyle(0);
pCMS->SetTextAlign(11);
pCMS->SetTextFont(42);
pCMS->SetTextSize(0.04);
pCMS->AddText("CMS Phase 2 #it{Preliminary}                    ");
TLegend *leg=new TLegend(0.3582943,0.7051483,0.55025753,0.9049564,NULL,"brNDC");
leg->SetTextFont(62);
leg->SetLineColor(1);
leg->SetLineStyle(1);
leg->SetLineWidth(3);
leg->SetFillColor(0);
leg->SetFillStyle(1001);
leg->SetShadowColor(0);
leg->SetDrawOption(0);
leg->SetBorderSize(0);
leg->SetTextSize(0.03);
THStack *hallbkg=new THStack("hallbkg",Variable);
hs1->SetFillStyle(1);
hs1->SetLineColor(11);
char h1L_sig[100];
const char *h1_L_sig;
h1_L_sig=sig_proc1.c_str();
sprintf(h1L_sig,"%s",h1_L_sig);
leg->AddEntry(hs1,h1L_sig,"l");
TCanvas *c=new TCanvas(Cname,Cname);
c->cd();
hs1->Scale(1/hs1->Integral());
hs1->Draw("same");
txtGen->Draw();
pCMS->Draw();
leg->Draw();
c->Write();
}

void shapePlotter::plotS1B0D1( string VarName,TPaveText *txtGen , TH1F *hs1,  string sig_proc1, 
TH1F *hd, string proc_data){
using namespace std;
TStyle *gStyle = new TStyle("gStyle","Style for P-TDR");
setStyle st;
st.SetPars(gStyle);
TPaveText *pCMS = new TPaveText(0.132107,0.9308003,0.8327759,0.9923583,"brNDC");
pCMS->SetBorderSize(0);
pCMS->SetFillStyle(0);
pCMS->SetTextAlign(11);
pCMS->SetTextFont(42);
pCMS->SetTextSize(0.04);
pCMS->AddText("CMS Phase 2 #it{Preliminary}                   ");
TLegend *leg=new TLegend(0.3582943,0.7051483,0.55025753,0.9049564,NULL,"brNDC");
leg->SetTextFont(62);
leg->SetLineColor(1);
leg->SetLineStyle(1);
leg->SetLineWidth(3);
leg->SetFillColor(0);
leg->SetFillStyle(1001);
leg->SetShadowColor(0);
leg->SetDrawOption(0);
leg->SetBorderSize(0);
leg->SetTextSize(0.03);
char Variable[100];
char Cname[100];
const char *Var_Name;
Var_Name=VarName.c_str();
sprintf(Variable," ;%s;Events",Var_Name);
sprintf(Cname,"%s",Var_Name);
THStack *hallbkg=new THStack("hallbkg",Variable);
hs1->SetFillStyle(1);
hs1->SetLineColor(11);
char h1L_sig[100];
const char *h1_L_sig;
h1_L_sig=sig_proc1.c_str();
sprintf(h1L_sig,"%s",h1_L_sig);
leg->AddEntry(hs1,h1L_sig,"l");
hd->SetLineColor(1);
hd->SetMarkerStyle(20);
char hL_data[100];
const char *h_L_data;
h_L_sig=proc_data.c_str();
sprintf(hL_data,"%s",h_L_sig);
leg->AddEntry(hd,hL_data,"p");
TCanvas *c=new TCanvas(Cname,Cname);
c->cd();
hs1->Scale(1/hs1->Integral());
hs1->Draw("same");
hd->Draw("P,E1 SAME");
txtGen->Draw();
pCMS->Draw();
leg->Draw();
c->Write();
}

void shapePlotter::plotS1B1D0( string VarName,TPaveText *txtGen , TH1F *hs1 , string sig_proc1
,  TH1F *hb1  , string bkg_proc1 ){
using namespace std;
TStyle *gStyle = new TStyle("gStyle","Style for P-TDR");
setStyle st;
st.SetPars(gStyle);
char Variable[100];
char Cname[100];
const char *Var_Name;
Var_Name=VarName.c_str();
sprintf(Variable," ;%s; Events",Var_Name);
sprintf(Cname,"%s",Var_Name);
TPaveText *pCMS = new TPaveText(0.132107,0.9308003,0.8327759,0.9923583,"brNDC");
pCMS->SetBorderSize(0);
pCMS->SetFillStyle(0);
pCMS->SetTextAlign(11);
pCMS->SetTextFont(42);
pCMS->SetTextSize(0.04);
pCMS->AddText("CMS Phase 2 #it{Preliminary}                    ");
TLegend *leg=new TLegend(0.3582943,0.7051483,0.55025753,0.9049564,NULL,"brNDC");
leg->SetTextFont(62);
leg->SetLineColor(1);
leg->SetLineStyle(1);
leg->SetLineWidth(3);
leg->SetFillColor(0);
leg->SetFillStyle(1001);
leg->SetShadowColor(0);
leg->SetDrawOption(0);
leg->SetBorderSize(0);
leg->SetTextSize(0.03);
THStack *hallbkg=new THStack("hallbkg",Variable);
hb1->SetLineColor(1);
hallbkg->Add(hb1);
char h1L_bkg[100];
const char *h1_L_bkg;
h1_L_bkg=bkg_proc1.c_str();
sprintf(h1L_bkg,"%s",h1_L_bkg);
leg->AddEntry(hb1,h1L_bkg,"l");
hs1->SetFillStyle(1);
hs1->SetLineColor(11);
char h1L_sig[100];
const char *h1_L_sig;
h1_L_sig=sig_proc1.c_str();
sprintf(h1L_sig,"%s",h1_L_sig);
leg->AddEntry(hs1,h1L_sig,"l");
TCanvas *c=new TCanvas(Cname,Cname);
c->cd();
hb1->Scale(1/hb1->Integral());
hb1->Draw("same");
hs1->Scale(1/hs1->Integral());
hs1->Draw("same");
txtGen->Draw();
pCMS->Draw();
leg->Draw();
c->Write();
}

void shapePlotter::plotS1B1D1( string VarName,TPaveText *txtGen , TH1F *hs1,  string sig_proc1, 
TH1F *hb1,  string bkg_proc1, 
TH1F *hd, string proc_data){
using namespace std;
TStyle *gStyle = new TStyle("gStyle","Style for P-TDR");
setStyle st;
st.SetPars(gStyle);
TPaveText *pCMS = new TPaveText(0.132107,0.9308003,0.8327759,0.9923583,"brNDC");
pCMS->SetBorderSize(0);
pCMS->SetFillStyle(0);
pCMS->SetTextAlign(11);
pCMS->SetTextFont(42);
pCMS->SetTextSize(0.04);
pCMS->AddText("CMS Phase 2 #it{Preliminary}                   ");
TLegend *leg=new TLegend(0.3582943,0.7051483,0.55025753,0.9049564,NULL,"brNDC");
leg->SetTextFont(62);
leg->SetLineColor(1);
leg->SetLineStyle(1);
leg->SetLineWidth(3);
leg->SetFillColor(0);
leg->SetFillStyle(1001);
leg->SetShadowColor(0);
leg->SetDrawOption(0);
leg->SetBorderSize(0);
leg->SetTextSize(0.03);
char Variable[100];
char Cname[100];
const char *Var_Name;
Var_Name=VarName.c_str();
sprintf(Variable," ;%s;Events",Var_Name);
sprintf(Cname,"%s",Var_Name);
THStack *hallbkg=new THStack("hallbkg",Variable);
hb1->SetLineColor(1);
hallbkg->Add(hb1);
char h1L_bkg[100];
const char *h1_L_bkg;
h1_L_bkg=bkg_proc1.c_str();
sprintf(h1L_bkg,"%s",h1_L_bkg);
leg->AddEntry(hb1,h1L_bkg,"l");
hs1->SetFillStyle(1);
hs1->SetLineColor(11);
char h1L_sig[100];
const char *h1_L_sig;
h1_L_sig=sig_proc1.c_str();
sprintf(h1L_sig,"%s",h1_L_sig);
leg->AddEntry(hs1,h1L_sig,"l");
hd->SetLineColor(1);
hd->SetMarkerStyle(20);
char hL_data[100];
const char *h_L_data;
h_L_sig=proc_data.c_str();
sprintf(hL_data,"%s",h_L_sig);
leg->AddEntry(hd,hL_data,"p");
TCanvas *c=new TCanvas(Cname,Cname);
c->cd();
hb1->Scale(1/hb1->Integral());
hb1->Draw("same");
hs1->Scale(1/hs1->Integral());
hs1->Draw("same");
hd->Draw("P,E1 SAME");
txtGen->Draw();
pCMS->Draw();
leg->Draw();
c->Write();
}

void shapePlotter::plotS1B2D0( string VarName,TPaveText *txtGen , TH1F *hs1 , string sig_proc1
,  TH1F *hb1  , string bkg_proc1 ,  TH1F *hb2  , string bkg_proc2 ){
using namespace std;
TStyle *gStyle = new TStyle("gStyle","Style for P-TDR");
setStyle st;
st.SetPars(gStyle);
char Variable[100];
char Cname[100];
const char *Var_Name;
Var_Name=VarName.c_str();
sprintf(Variable," ;%s; Events",Var_Name);
sprintf(Cname,"%s",Var_Name);
TPaveText *pCMS = new TPaveText(0.132107,0.9308003,0.8327759,0.9923583,"brNDC");
pCMS->SetBorderSize(0);
pCMS->SetFillStyle(0);
pCMS->SetTextAlign(11);
pCMS->SetTextFont(42);
pCMS->SetTextSize(0.04);
pCMS->AddText("CMS Phase 2 #it{Preliminary}                    ");
TLegend *leg=new TLegend(0.3582943,0.7051483,0.55025753,0.9049564,NULL,"brNDC");
leg->SetTextFont(62);
leg->SetLineColor(1);
leg->SetLineStyle(1);
leg->SetLineWidth(3);
leg->SetFillColor(0);
leg->SetFillStyle(1001);
leg->SetShadowColor(0);
leg->SetDrawOption(0);
leg->SetBorderSize(0);
leg->SetTextSize(0.03);
THStack *hallbkg=new THStack("hallbkg",Variable);
hb1->SetLineColor(1);
hallbkg->Add(hb1);
char h1L_bkg[100];
const char *h1_L_bkg;
h1_L_bkg=bkg_proc1.c_str();
sprintf(h1L_bkg,"%s",h1_L_bkg);
leg->AddEntry(hb1,h1L_bkg,"l");
hb2->SetLineColor(2);
hallbkg->Add(hb2);
char h2L_bkg[100];
const char *h2_L_bkg;
h2_L_bkg=bkg_proc2.c_str();
sprintf(h2L_bkg,"%s",h2_L_bkg);
leg->AddEntry(hb2,h2L_bkg,"l");
hs1->SetFillStyle(1);
hs1->SetLineColor(11);
char h1L_sig[100];
const char *h1_L_sig;
h1_L_sig=sig_proc1.c_str();
sprintf(h1L_sig,"%s",h1_L_sig);
leg->AddEntry(hs1,h1L_sig,"l");
TCanvas *c=new TCanvas(Cname,Cname);
c->cd();
hb1->Scale(1/hb1->Integral());
hb1->Draw("same");
hb2->Scale(1/hb2->Integral());
hb2->Draw("same");
hs1->Scale(1/hs1->Integral());
hs1->Draw("same");
txtGen->Draw();
pCMS->Draw();
leg->Draw();
c->Write();
}

void shapePlotter::plotS1B2D1( string VarName,TPaveText *txtGen , TH1F *hs1,  string sig_proc1, 
TH1F *hb1,  string bkg_proc1, 
TH1F *hb2,  string bkg_proc2, 
TH1F *hd, string proc_data){
using namespace std;
TStyle *gStyle = new TStyle("gStyle","Style for P-TDR");
setStyle st;
st.SetPars(gStyle);
TPaveText *pCMS = new TPaveText(0.132107,0.9308003,0.8327759,0.9923583,"brNDC");
pCMS->SetBorderSize(0);
pCMS->SetFillStyle(0);
pCMS->SetTextAlign(11);
pCMS->SetTextFont(42);
pCMS->SetTextSize(0.04);
pCMS->AddText("CMS Phase 2 #it{Preliminary}                   ");
TLegend *leg=new TLegend(0.3582943,0.7051483,0.55025753,0.9049564,NULL,"brNDC");
leg->SetTextFont(62);
leg->SetLineColor(1);
leg->SetLineStyle(1);
leg->SetLineWidth(3);
leg->SetFillColor(0);
leg->SetFillStyle(1001);
leg->SetShadowColor(0);
leg->SetDrawOption(0);
leg->SetBorderSize(0);
leg->SetTextSize(0.03);
char Variable[100];
char Cname[100];
const char *Var_Name;
Var_Name=VarName.c_str();
sprintf(Variable," ;%s;Events",Var_Name);
sprintf(Cname,"%s",Var_Name);
THStack *hallbkg=new THStack("hallbkg",Variable);
hb1->SetLineColor(1);
hallbkg->Add(hb1);
char h1L_bkg[100];
const char *h1_L_bkg;
h1_L_bkg=bkg_proc1.c_str();
sprintf(h1L_bkg,"%s",h1_L_bkg);
leg->AddEntry(hb1,h1L_bkg,"l");
hb2->SetLineColor(2);
hallbkg->Add(hb2);
char h2L_bkg[100];
const char *h2_L_bkg;
h2_L_bkg=bkg_proc2.c_str();
sprintf(h2L_bkg,"%s",h2_L_bkg);
leg->AddEntry(hb2,h2L_bkg,"l");
hs1->SetFillStyle(1);
hs1->SetLineColor(11);
char h1L_sig[100];
const char *h1_L_sig;
h1_L_sig=sig_proc1.c_str();
sprintf(h1L_sig,"%s",h1_L_sig);
leg->AddEntry(hs1,h1L_sig,"l");
hd->SetLineColor(1);
hd->SetMarkerStyle(20);
char hL_data[100];
const char *h_L_data;
h_L_sig=proc_data.c_str();
sprintf(hL_data,"%s",h_L_sig);
leg->AddEntry(hd,hL_data,"p");
TCanvas *c=new TCanvas(Cname,Cname);
c->cd();
hb1->Scale(1/hb1->Integral());
hb1->Draw("same");
hb2->Scale(1/hb2->Integral());
hb2->Draw("same");
hs1->Scale(1/hs1->Integral());
hs1->Draw("same");
hd->Draw("P,E1 SAME");
txtGen->Draw();
pCMS->Draw();
leg->Draw();
c->Write();
}

void shapePlotter::plotS1B3D0( string VarName,TPaveText *txtGen , TH1F *hs1 , string sig_proc1
,  TH1F *hb1  , string bkg_proc1 ,  TH1F *hb2  , string bkg_proc2 ,  TH1F *hb3  , string bkg_proc3 ){
using namespace std;
TStyle *gStyle = new TStyle("gStyle","Style for P-TDR");
setStyle st;
st.SetPars(gStyle);
char Variable[100];
char Cname[100];
const char *Var_Name;
Var_Name=VarName.c_str();
sprintf(Variable," ;%s; Events",Var_Name);
sprintf(Cname,"%s",Var_Name);
TPaveText *pCMS = new TPaveText(0.132107,0.9308003,0.8327759,0.9923583,"brNDC");
pCMS->SetBorderSize(0);
pCMS->SetFillStyle(0);
pCMS->SetTextAlign(11);
pCMS->SetTextFont(42);
pCMS->SetTextSize(0.04);
pCMS->AddText("CMS Phase 2 #it{Preliminary}                    ");
TLegend *leg=new TLegend(0.3582943,0.7051483,0.55025753,0.9049564,NULL,"brNDC");
leg->SetTextFont(62);
leg->SetLineColor(1);
leg->SetLineStyle(1);
leg->SetLineWidth(3);
leg->SetFillColor(0);
leg->SetFillStyle(1001);
leg->SetShadowColor(0);
leg->SetDrawOption(0);
leg->SetBorderSize(0);
leg->SetTextSize(0.03);
THStack *hallbkg=new THStack("hallbkg",Variable);
hb1->SetLineColor(1);
hallbkg->Add(hb1);
char h1L_bkg[100];
const char *h1_L_bkg;
h1_L_bkg=bkg_proc1.c_str();
sprintf(h1L_bkg,"%s",h1_L_bkg);
leg->AddEntry(hb1,h1L_bkg,"l");
hb2->SetLineColor(2);
hallbkg->Add(hb2);
char h2L_bkg[100];
const char *h2_L_bkg;
h2_L_bkg=bkg_proc2.c_str();
sprintf(h2L_bkg,"%s",h2_L_bkg);
leg->AddEntry(hb2,h2L_bkg,"l");
hb3->SetLineColor(3);
hallbkg->Add(hb3);
char h3L_bkg[100];
const char *h3_L_bkg;
h3_L_bkg=bkg_proc3.c_str();
sprintf(h3L_bkg,"%s",h3_L_bkg);
leg->AddEntry(hb3,h3L_bkg,"l");
hs1->SetFillStyle(1);
hs1->SetLineColor(11);
char h1L_sig[100];
const char *h1_L_sig;
h1_L_sig=sig_proc1.c_str();
sprintf(h1L_sig,"%s",h1_L_sig);
leg->AddEntry(hs1,h1L_sig,"l");
TCanvas *c=new TCanvas(Cname,Cname);
c->cd();
hb1->Scale(1/hb1->Integral());
hb1->Draw("same");
hb2->Scale(1/hb2->Integral());
hb2->Draw("same");
hb3->Scale(1/hb3->Integral());
hb3->Draw("same");
hs1->Scale(1/hs1->Integral());
hs1->Draw("same");
txtGen->Draw();
pCMS->Draw();
leg->Draw();
c->Write();
}

void shapePlotter::plotS1B3D1( string VarName,TPaveText *txtGen , TH1F *hs1,  string sig_proc1, 
TH1F *hb1,  string bkg_proc1, 
TH1F *hb2,  string bkg_proc2, 
TH1F *hb3,  string bkg_proc3, 
TH1F *hd, string proc_data){
using namespace std;
TStyle *gStyle = new TStyle("gStyle","Style for P-TDR");
setStyle st;
st.SetPars(gStyle);
TPaveText *pCMS = new TPaveText(0.132107,0.9308003,0.8327759,0.9923583,"brNDC");
pCMS->SetBorderSize(0);
pCMS->SetFillStyle(0);
pCMS->SetTextAlign(11);
pCMS->SetTextFont(42);
pCMS->SetTextSize(0.04);
pCMS->AddText("CMS Phase 2 #it{Preliminary}                   ");
TLegend *leg=new TLegend(0.3582943,0.7051483,0.55025753,0.9049564,NULL,"brNDC");
leg->SetTextFont(62);
leg->SetLineColor(1);
leg->SetLineStyle(1);
leg->SetLineWidth(3);
leg->SetFillColor(0);
leg->SetFillStyle(1001);
leg->SetShadowColor(0);
leg->SetDrawOption(0);
leg->SetBorderSize(0);
leg->SetTextSize(0.03);
char Variable[100];
char Cname[100];
const char *Var_Name;
Var_Name=VarName.c_str();
sprintf(Variable," ;%s;Events",Var_Name);
sprintf(Cname,"%s",Var_Name);
THStack *hallbkg=new THStack("hallbkg",Variable);
hb1->SetLineColor(1);
hallbkg->Add(hb1);
char h1L_bkg[100];
const char *h1_L_bkg;
h1_L_bkg=bkg_proc1.c_str();
sprintf(h1L_bkg,"%s",h1_L_bkg);
leg->AddEntry(hb1,h1L_bkg,"l");
hb2->SetLineColor(2);
hallbkg->Add(hb2);
char h2L_bkg[100];
const char *h2_L_bkg;
h2_L_bkg=bkg_proc2.c_str();
sprintf(h2L_bkg,"%s",h2_L_bkg);
leg->AddEntry(hb2,h2L_bkg,"l");
hb3->SetLineColor(3);
hallbkg->Add(hb3);
char h3L_bkg[100];
const char *h3_L_bkg;
h3_L_bkg=bkg_proc3.c_str();
sprintf(h3L_bkg,"%s",h3_L_bkg);
leg->AddEntry(hb3,h3L_bkg,"l");
hs1->SetFillStyle(1);
hs1->SetLineColor(11);
char h1L_sig[100];
const char *h1_L_sig;
h1_L_sig=sig_proc1.c_str();
sprintf(h1L_sig,"%s",h1_L_sig);
leg->AddEntry(hs1,h1L_sig,"l");
hd->SetLineColor(1);
hd->SetMarkerStyle(20);
char hL_data[100];
const char *h_L_data;
h_L_sig=proc_data.c_str();
sprintf(hL_data,"%s",h_L_sig);
leg->AddEntry(hd,hL_data,"p");
TCanvas *c=new TCanvas(Cname,Cname);
c->cd();
hb1->Scale(1/hb1->Integral());
hb1->Draw("same");
hb2->Scale(1/hb2->Integral());
hb2->Draw("same");
hb3->Scale(1/hb3->Integral());
hb3->Draw("same");
hs1->Scale(1/hs1->Integral());
hs1->Draw("same");
hd->Draw("P,E1 SAME");
txtGen->Draw();
pCMS->Draw();
leg->Draw();
c->Write();
}

void shapePlotter::plotS1B4D0( string VarName,TPaveText *txtGen , TH1F *hs1 , string sig_proc1
,  TH1F *hb1  , string bkg_proc1 ,  TH1F *hb2  , string bkg_proc2 ,  TH1F *hb3  , string bkg_proc3 ,  TH1F *hb4  , string bkg_proc4 ){
using namespace std;
TStyle *gStyle = new TStyle("gStyle","Style for P-TDR");
setStyle st;
st.SetPars(gStyle);
char Variable[100];
char Cname[100];
const char *Var_Name;
Var_Name=VarName.c_str();
sprintf(Variable," ;%s; Events",Var_Name);
sprintf(Cname,"%s",Var_Name);
TPaveText *pCMS = new TPaveText(0.132107,0.9308003,0.8327759,0.9923583,"brNDC");
pCMS->SetBorderSize(0);
pCMS->SetFillStyle(0);
pCMS->SetTextAlign(11);
pCMS->SetTextFont(42);
pCMS->SetTextSize(0.04);
pCMS->AddText("CMS Phase 2 #it{Preliminary}                    ");
TLegend *leg=new TLegend(0.3582943,0.7051483,0.55025753,0.9049564,NULL,"brNDC");
leg->SetTextFont(62);
leg->SetLineColor(1);
leg->SetLineStyle(1);
leg->SetLineWidth(3);
leg->SetFillColor(0);
leg->SetFillStyle(1001);
leg->SetShadowColor(0);
leg->SetDrawOption(0);
leg->SetBorderSize(0);
leg->SetTextSize(0.03);
THStack *hallbkg=new THStack("hallbkg",Variable);
hb1->SetLineColor(1);
hallbkg->Add(hb1);
char h1L_bkg[100];
const char *h1_L_bkg;
h1_L_bkg=bkg_proc1.c_str();
sprintf(h1L_bkg,"%s",h1_L_bkg);
leg->AddEntry(hb1,h1L_bkg,"l");
hb2->SetLineColor(2);
hallbkg->Add(hb2);
char h2L_bkg[100];
const char *h2_L_bkg;
h2_L_bkg=bkg_proc2.c_str();
sprintf(h2L_bkg,"%s",h2_L_bkg);
leg->AddEntry(hb2,h2L_bkg,"l");
hb3->SetLineColor(3);
hallbkg->Add(hb3);
char h3L_bkg[100];
const char *h3_L_bkg;
h3_L_bkg=bkg_proc3.c_str();
sprintf(h3L_bkg,"%s",h3_L_bkg);
leg->AddEntry(hb3,h3L_bkg,"l");
hb4->SetLineColor(4);
hallbkg->Add(hb4);
char h4L_bkg[100];
const char *h4_L_bkg;
h4_L_bkg=bkg_proc4.c_str();
sprintf(h4L_bkg,"%s",h4_L_bkg);
leg->AddEntry(hb4,h4L_bkg,"l");
hs1->SetFillStyle(1);
hs1->SetLineColor(11);
char h1L_sig[100];
const char *h1_L_sig;
h1_L_sig=sig_proc1.c_str();
sprintf(h1L_sig,"%s",h1_L_sig);
leg->AddEntry(hs1,h1L_sig,"l");
TCanvas *c=new TCanvas(Cname,Cname);
c->cd();
hb1->Scale(1/hb1->Integral());
hb1->Draw("same");
hb2->Scale(1/hb2->Integral());
hb2->Draw("same");
hb3->Scale(1/hb3->Integral());
hb3->Draw("same");
hb4->Scale(1/hb4->Integral());
hb4->Draw("same");
hs1->Scale(1/hs1->Integral());
hs1->Draw("same");
txtGen->Draw();
pCMS->Draw();
leg->Draw();
c->Write();
}

void shapePlotter::plotS1B4D1( string VarName,TPaveText *txtGen , TH1F *hs1,  string sig_proc1, 
TH1F *hb1,  string bkg_proc1, 
TH1F *hb2,  string bkg_proc2, 
TH1F *hb3,  string bkg_proc3, 
TH1F *hb4,  string bkg_proc4, 
TH1F *hd, string proc_data){
using namespace std;
TStyle *gStyle = new TStyle("gStyle","Style for P-TDR");
setStyle st;
st.SetPars(gStyle);
TPaveText *pCMS = new TPaveText(0.132107,0.9308003,0.8327759,0.9923583,"brNDC");
pCMS->SetBorderSize(0);
pCMS->SetFillStyle(0);
pCMS->SetTextAlign(11);
pCMS->SetTextFont(42);
pCMS->SetTextSize(0.04);
pCMS->AddText("CMS Phase 2 #it{Preliminary}                   ");
TLegend *leg=new TLegend(0.3582943,0.7051483,0.55025753,0.9049564,NULL,"brNDC");
leg->SetTextFont(62);
leg->SetLineColor(1);
leg->SetLineStyle(1);
leg->SetLineWidth(3);
leg->SetFillColor(0);
leg->SetFillStyle(1001);
leg->SetShadowColor(0);
leg->SetDrawOption(0);
leg->SetBorderSize(0);
leg->SetTextSize(0.03);
char Variable[100];
char Cname[100];
const char *Var_Name;
Var_Name=VarName.c_str();
sprintf(Variable," ;%s;Events",Var_Name);
sprintf(Cname,"%s",Var_Name);
THStack *hallbkg=new THStack("hallbkg",Variable);
hb1->SetLineColor(1);
hallbkg->Add(hb1);
char h1L_bkg[100];
const char *h1_L_bkg;
h1_L_bkg=bkg_proc1.c_str();
sprintf(h1L_bkg,"%s",h1_L_bkg);
leg->AddEntry(hb1,h1L_bkg,"l");
hb2->SetLineColor(2);
hallbkg->Add(hb2);
char h2L_bkg[100];
const char *h2_L_bkg;
h2_L_bkg=bkg_proc2.c_str();
sprintf(h2L_bkg,"%s",h2_L_bkg);
leg->AddEntry(hb2,h2L_bkg,"l");
hb3->SetLineColor(3);
hallbkg->Add(hb3);
char h3L_bkg[100];
const char *h3_L_bkg;
h3_L_bkg=bkg_proc3.c_str();
sprintf(h3L_bkg,"%s",h3_L_bkg);
leg->AddEntry(hb3,h3L_bkg,"l");
hb4->SetLineColor(4);
hallbkg->Add(hb4);
char h4L_bkg[100];
const char *h4_L_bkg;
h4_L_bkg=bkg_proc4.c_str();
sprintf(h4L_bkg,"%s",h4_L_bkg);
leg->AddEntry(hb4,h4L_bkg,"l");
hs1->SetFillStyle(1);
hs1->SetLineColor(11);
char h1L_sig[100];
const char *h1_L_sig;
h1_L_sig=sig_proc1.c_str();
sprintf(h1L_sig,"%s",h1_L_sig);
leg->AddEntry(hs1,h1L_sig,"l");
hd->SetLineColor(1);
hd->SetMarkerStyle(20);
char hL_data[100];
const char *h_L_data;
h_L_sig=proc_data.c_str();
sprintf(hL_data,"%s",h_L_sig);
leg->AddEntry(hd,hL_data,"p");
TCanvas *c=new TCanvas(Cname,Cname);
c->cd();
hb1->Scale(1/hb1->Integral());
hb1->Draw("same");
hb2->Scale(1/hb2->Integral());
hb2->Draw("same");
hb3->Scale(1/hb3->Integral());
hb3->Draw("same");
hb4->Scale(1/hb4->Integral());
hb4->Draw("same");
hs1->Scale(1/hs1->Integral());
hs1->Draw("same");
hd->Draw("P,E1 SAME");
txtGen->Draw();
pCMS->Draw();
leg->Draw();
c->Write();
}

void shapePlotter::plotS2B0D0( string VarName,TPaveText *txtGen , TH1F *hs1 , string sig_proc1
, TH1F *hs2 , string sig_proc2
){
using namespace std;
TStyle *gStyle = new TStyle("gStyle","Style for P-TDR");
setStyle st;
st.SetPars(gStyle);
char Variable[100];
char Cname[100];
const char *Var_Name;
Var_Name=VarName.c_str();
sprintf(Variable," ;%s; Events",Var_Name);
sprintf(Cname,"%s",Var_Name);
TPaveText *pCMS = new TPaveText(0.132107,0.9308003,0.8327759,0.9923583,"brNDC");
pCMS->SetBorderSize(0);
pCMS->SetFillStyle(0);
pCMS->SetTextAlign(11);
pCMS->SetTextFont(42);
pCMS->SetTextSize(0.04);
pCMS->AddText("CMS Phase 2 #it{Preliminary}                    ");
TLegend *leg=new TLegend(0.3582943,0.7051483,0.55025753,0.9049564,NULL,"brNDC");
leg->SetTextFont(62);
leg->SetLineColor(1);
leg->SetLineStyle(1);
leg->SetLineWidth(3);
leg->SetFillColor(0);
leg->SetFillStyle(1001);
leg->SetShadowColor(0);
leg->SetDrawOption(0);
leg->SetBorderSize(0);
leg->SetTextSize(0.03);
THStack *hallbkg=new THStack("hallbkg",Variable);
hs1->SetFillStyle(1);
hs1->SetLineColor(11);
char h1L_sig[100];
const char *h1_L_sig;
h1_L_sig=sig_proc1.c_str();
sprintf(h1L_sig,"%s",h1_L_sig);
leg->AddEntry(hs1,h1L_sig,"l");
hs2->SetFillStyle(1);
hs2->SetLineColor(12);
char h2L_sig[100];
const char *h2_L_sig;
h2_L_sig=sig_proc2.c_str();
sprintf(h2L_sig,"%s",h2_L_sig);
leg->AddEntry(hs2,h2L_sig,"l");
TCanvas *c=new TCanvas(Cname,Cname);
c->cd();
hs1->Scale(1/hs1->Integral());
hs1->Draw("same");
hs2->Scale(1/hs2->Integral());
hs2->Draw("same");
txtGen->Draw();
pCMS->Draw();
leg->Draw();
c->Write();
}

void shapePlotter::plotS2B0D1( string VarName,TPaveText *txtGen , TH1F *hs1,  string sig_proc1, 
TH1F *hs2,  string sig_proc2, 
TH1F *hd, string proc_data){
using namespace std;
TStyle *gStyle = new TStyle("gStyle","Style for P-TDR");
setStyle st;
st.SetPars(gStyle);
TPaveText *pCMS = new TPaveText(0.132107,0.9308003,0.8327759,0.9923583,"brNDC");
pCMS->SetBorderSize(0);
pCMS->SetFillStyle(0);
pCMS->SetTextAlign(11);
pCMS->SetTextFont(42);
pCMS->SetTextSize(0.04);
pCMS->AddText("CMS Phase 2 #it{Preliminary}                   ");
TLegend *leg=new TLegend(0.3582943,0.7051483,0.55025753,0.9049564,NULL,"brNDC");
leg->SetTextFont(62);
leg->SetLineColor(1);
leg->SetLineStyle(1);
leg->SetLineWidth(3);
leg->SetFillColor(0);
leg->SetFillStyle(1001);
leg->SetShadowColor(0);
leg->SetDrawOption(0);
leg->SetBorderSize(0);
leg->SetTextSize(0.03);
char Variable[100];
char Cname[100];
const char *Var_Name;
Var_Name=VarName.c_str();
sprintf(Variable," ;%s;Events",Var_Name);
sprintf(Cname,"%s",Var_Name);
THStack *hallbkg=new THStack("hallbkg",Variable);
hs1->SetFillStyle(1);
hs1->SetLineColor(11);
char h1L_sig[100];
const char *h1_L_sig;
h1_L_sig=sig_proc1.c_str();
sprintf(h1L_sig,"%s",h1_L_sig);
leg->AddEntry(hs1,h1L_sig,"l");
hs2->SetFillStyle(1);
hs2->SetLineColor(12);
char h2L_sig[100];
const char *h2_L_sig;
h2_L_sig=sig_proc2.c_str();
sprintf(h2L_sig,"%s",h2_L_sig);
leg->AddEntry(hs2,h2L_sig,"l");
hd->SetLineColor(1);
hd->SetMarkerStyle(20);
char hL_data[100];
const char *h_L_data;
h_L_sig=proc_data.c_str();
sprintf(hL_data,"%s",h_L_sig);
leg->AddEntry(hd,hL_data,"p");
TCanvas *c=new TCanvas(Cname,Cname);
c->cd();
hs1->Scale(1/hs1->Integral());
hs1->Draw("same");
hs2->Scale(1/hs2->Integral());
hs2->Draw("same");
hd->Draw("P,E1 SAME");
txtGen->Draw();
pCMS->Draw();
leg->Draw();
c->Write();
}

void shapePlotter::plotS2B1D0( string VarName,TPaveText *txtGen , TH1F *hs1 , string sig_proc1
, TH1F *hs2 , string sig_proc2
,  TH1F *hb1  , string bkg_proc1 ){
using namespace std;
TStyle *gStyle = new TStyle("gStyle","Style for P-TDR");
setStyle st;
st.SetPars(gStyle);
char Variable[100];
char Cname[100];
const char *Var_Name;
Var_Name=VarName.c_str();
sprintf(Variable," ;%s; Events",Var_Name);
sprintf(Cname,"%s",Var_Name);
TPaveText *pCMS = new TPaveText(0.132107,0.9308003,0.8327759,0.9923583,"brNDC");
pCMS->SetBorderSize(0);
pCMS->SetFillStyle(0);
pCMS->SetTextAlign(11);
pCMS->SetTextFont(42);
pCMS->SetTextSize(0.04);
pCMS->AddText("CMS Phase 2 #it{Preliminary}                    ");
TLegend *leg=new TLegend(0.3582943,0.7051483,0.55025753,0.9049564,NULL,"brNDC");
leg->SetTextFont(62);
leg->SetLineColor(1);
leg->SetLineStyle(1);
leg->SetLineWidth(3);
leg->SetFillColor(0);
leg->SetFillStyle(1001);
leg->SetShadowColor(0);
leg->SetDrawOption(0);
leg->SetBorderSize(0);
leg->SetTextSize(0.03);
THStack *hallbkg=new THStack("hallbkg",Variable);
hb1->SetLineColor(1);
hallbkg->Add(hb1);
char h1L_bkg[100];
const char *h1_L_bkg;
h1_L_bkg=bkg_proc1.c_str();
sprintf(h1L_bkg,"%s",h1_L_bkg);
leg->AddEntry(hb1,h1L_bkg,"l");
hs1->SetFillStyle(1);
hs1->SetLineColor(11);
char h1L_sig[100];
const char *h1_L_sig;
h1_L_sig=sig_proc1.c_str();
sprintf(h1L_sig,"%s",h1_L_sig);
leg->AddEntry(hs1,h1L_sig,"l");
hs2->SetFillStyle(1);
hs2->SetLineColor(12);
char h2L_sig[100];
const char *h2_L_sig;
h2_L_sig=sig_proc2.c_str();
sprintf(h2L_sig,"%s",h2_L_sig);
leg->AddEntry(hs2,h2L_sig,"l");
TCanvas *c=new TCanvas(Cname,Cname);
c->cd();
hb1->Scale(1/hb1->Integral());
hb1->Draw("same");
hs1->Scale(1/hs1->Integral());
hs1->Draw("same");
hs2->Scale(1/hs2->Integral());
hs2->Draw("same");
txtGen->Draw();
pCMS->Draw();
leg->Draw();
c->Write();
}

void shapePlotter::plotS2B1D1( string VarName,TPaveText *txtGen , TH1F *hs1,  string sig_proc1, 
TH1F *hs2,  string sig_proc2, 
TH1F *hb1,  string bkg_proc1, 
TH1F *hd, string proc_data){
using namespace std;
TStyle *gStyle = new TStyle("gStyle","Style for P-TDR");
setStyle st;
st.SetPars(gStyle);
TPaveText *pCMS = new TPaveText(0.132107,0.9308003,0.8327759,0.9923583,"brNDC");
pCMS->SetBorderSize(0);
pCMS->SetFillStyle(0);
pCMS->SetTextAlign(11);
pCMS->SetTextFont(42);
pCMS->SetTextSize(0.04);
pCMS->AddText("CMS Phase 2 #it{Preliminary}                   ");
TLegend *leg=new TLegend(0.3582943,0.7051483,0.55025753,0.9049564,NULL,"brNDC");
leg->SetTextFont(62);
leg->SetLineColor(1);
leg->SetLineStyle(1);
leg->SetLineWidth(3);
leg->SetFillColor(0);
leg->SetFillStyle(1001);
leg->SetShadowColor(0);
leg->SetDrawOption(0);
leg->SetBorderSize(0);
leg->SetTextSize(0.03);
char Variable[100];
char Cname[100];
const char *Var_Name;
Var_Name=VarName.c_str();
sprintf(Variable," ;%s;Events",Var_Name);
sprintf(Cname,"%s",Var_Name);
THStack *hallbkg=new THStack("hallbkg",Variable);
hb1->SetLineColor(1);
hallbkg->Add(hb1);
char h1L_bkg[100];
const char *h1_L_bkg;
h1_L_bkg=bkg_proc1.c_str();
sprintf(h1L_bkg,"%s",h1_L_bkg);
leg->AddEntry(hb1,h1L_bkg,"l");
hs1->SetFillStyle(1);
hs1->SetLineColor(11);
char h1L_sig[100];
const char *h1_L_sig;
h1_L_sig=sig_proc1.c_str();
sprintf(h1L_sig,"%s",h1_L_sig);
leg->AddEntry(hs1,h1L_sig,"l");
hs2->SetFillStyle(1);
hs2->SetLineColor(12);
char h2L_sig[100];
const char *h2_L_sig;
h2_L_sig=sig_proc2.c_str();
sprintf(h2L_sig,"%s",h2_L_sig);
leg->AddEntry(hs2,h2L_sig,"l");
hd->SetLineColor(1);
hd->SetMarkerStyle(20);
char hL_data[100];
const char *h_L_data;
h_L_sig=proc_data.c_str();
sprintf(hL_data,"%s",h_L_sig);
leg->AddEntry(hd,hL_data,"p");
TCanvas *c=new TCanvas(Cname,Cname);
c->cd();
hb1->Scale(1/hb1->Integral());
hb1->Draw("same");
hs1->Scale(1/hs1->Integral());
hs1->Draw("same");
hs2->Scale(1/hs2->Integral());
hs2->Draw("same");
hd->Draw("P,E1 SAME");
txtGen->Draw();
pCMS->Draw();
leg->Draw();
c->Write();
}

void shapePlotter::plotS2B2D0( string VarName,TPaveText *txtGen , TH1F *hs1 , string sig_proc1
, TH1F *hs2 , string sig_proc2
,  TH1F *hb1  , string bkg_proc1 ,  TH1F *hb2  , string bkg_proc2 ){
using namespace std;
TStyle *gStyle = new TStyle("gStyle","Style for P-TDR");
setStyle st;
st.SetPars(gStyle);
char Variable[100];
char Cname[100];
const char *Var_Name;
Var_Name=VarName.c_str();
sprintf(Variable," ;%s; Events",Var_Name);
sprintf(Cname,"%s",Var_Name);
TPaveText *pCMS = new TPaveText(0.132107,0.9308003,0.8327759,0.9923583,"brNDC");
pCMS->SetBorderSize(0);
pCMS->SetFillStyle(0);
pCMS->SetTextAlign(11);
pCMS->SetTextFont(42);
pCMS->SetTextSize(0.04);
pCMS->AddText("CMS Phase 2 #it{Preliminary}                    ");
TLegend *leg=new TLegend(0.3582943,0.7051483,0.55025753,0.9049564,NULL,"brNDC");
leg->SetTextFont(62);
leg->SetLineColor(1);
leg->SetLineStyle(1);
leg->SetLineWidth(3);
leg->SetFillColor(0);
leg->SetFillStyle(1001);
leg->SetShadowColor(0);
leg->SetDrawOption(0);
leg->SetBorderSize(0);
leg->SetTextSize(0.03);
THStack *hallbkg=new THStack("hallbkg",Variable);
hb1->SetLineColor(1);
hallbkg->Add(hb1);
char h1L_bkg[100];
const char *h1_L_bkg;
h1_L_bkg=bkg_proc1.c_str();
sprintf(h1L_bkg,"%s",h1_L_bkg);
leg->AddEntry(hb1,h1L_bkg,"l");
hb2->SetLineColor(2);
hallbkg->Add(hb2);
char h2L_bkg[100];
const char *h2_L_bkg;
h2_L_bkg=bkg_proc2.c_str();
sprintf(h2L_bkg,"%s",h2_L_bkg);
leg->AddEntry(hb2,h2L_bkg,"l");
hs1->SetFillStyle(1);
hs1->SetLineColor(11);
char h1L_sig[100];
const char *h1_L_sig;
h1_L_sig=sig_proc1.c_str();
sprintf(h1L_sig,"%s",h1_L_sig);
leg->AddEntry(hs1,h1L_sig,"l");
hs2->SetFillStyle(1);
hs2->SetLineColor(12);
char h2L_sig[100];
const char *h2_L_sig;
h2_L_sig=sig_proc2.c_str();
sprintf(h2L_sig,"%s",h2_L_sig);
leg->AddEntry(hs2,h2L_sig,"l");
TCanvas *c=new TCanvas(Cname,Cname);
c->cd();
hb1->Scale(1/hb1->Integral());
hb1->Draw("same");
hb2->Scale(1/hb2->Integral());
hb2->Draw("same");
hs1->Scale(1/hs1->Integral());
hs1->Draw("same");
hs2->Scale(1/hs2->Integral());
hs2->Draw("same");
txtGen->Draw();
pCMS->Draw();
leg->Draw();
c->Write();
}

void shapePlotter::plotS2B2D1( string VarName,TPaveText *txtGen , TH1F *hs1,  string sig_proc1, 
TH1F *hs2,  string sig_proc2, 
TH1F *hb1,  string bkg_proc1, 
TH1F *hb2,  string bkg_proc2, 
TH1F *hd, string proc_data){
using namespace std;
TStyle *gStyle = new TStyle("gStyle","Style for P-TDR");
setStyle st;
st.SetPars(gStyle);
TPaveText *pCMS = new TPaveText(0.132107,0.9308003,0.8327759,0.9923583,"brNDC");
pCMS->SetBorderSize(0);
pCMS->SetFillStyle(0);
pCMS->SetTextAlign(11);
pCMS->SetTextFont(42);
pCMS->SetTextSize(0.04);
pCMS->AddText("CMS Phase 2 #it{Preliminary}                   ");
TLegend *leg=new TLegend(0.3582943,0.7051483,0.55025753,0.9049564,NULL,"brNDC");
leg->SetTextFont(62);
leg->SetLineColor(1);
leg->SetLineStyle(1);
leg->SetLineWidth(3);
leg->SetFillColor(0);
leg->SetFillStyle(1001);
leg->SetShadowColor(0);
leg->SetDrawOption(0);
leg->SetBorderSize(0);
leg->SetTextSize(0.03);
char Variable[100];
char Cname[100];
const char *Var_Name;
Var_Name=VarName.c_str();
sprintf(Variable," ;%s;Events",Var_Name);
sprintf(Cname,"%s",Var_Name);
THStack *hallbkg=new THStack("hallbkg",Variable);
hb1->SetLineColor(1);
hallbkg->Add(hb1);
char h1L_bkg[100];
const char *h1_L_bkg;
h1_L_bkg=bkg_proc1.c_str();
sprintf(h1L_bkg,"%s",h1_L_bkg);
leg->AddEntry(hb1,h1L_bkg,"l");
hb2->SetLineColor(2);
hallbkg->Add(hb2);
char h2L_bkg[100];
const char *h2_L_bkg;
h2_L_bkg=bkg_proc2.c_str();
sprintf(h2L_bkg,"%s",h2_L_bkg);
leg->AddEntry(hb2,h2L_bkg,"l");
hs1->SetFillStyle(1);
hs1->SetLineColor(11);
char h1L_sig[100];
const char *h1_L_sig;
h1_L_sig=sig_proc1.c_str();
sprintf(h1L_sig,"%s",h1_L_sig);
leg->AddEntry(hs1,h1L_sig,"l");
hs2->SetFillStyle(1);
hs2->SetLineColor(12);
char h2L_sig[100];
const char *h2_L_sig;
h2_L_sig=sig_proc2.c_str();
sprintf(h2L_sig,"%s",h2_L_sig);
leg->AddEntry(hs2,h2L_sig,"l");
hd->SetLineColor(1);
hd->SetMarkerStyle(20);
char hL_data[100];
const char *h_L_data;
h_L_sig=proc_data.c_str();
sprintf(hL_data,"%s",h_L_sig);
leg->AddEntry(hd,hL_data,"p");
TCanvas *c=new TCanvas(Cname,Cname);
c->cd();
hb1->Scale(1/hb1->Integral());
hb1->Draw("same");
hb2->Scale(1/hb2->Integral());
hb2->Draw("same");
hs1->Scale(1/hs1->Integral());
hs1->Draw("same");
hs2->Scale(1/hs2->Integral());
hs2->Draw("same");
hd->Draw("P,E1 SAME");
txtGen->Draw();
pCMS->Draw();
leg->Draw();
c->Write();
}

void shapePlotter::plotS2B3D0( string VarName,TPaveText *txtGen , TH1F *hs1 , string sig_proc1
, TH1F *hs2 , string sig_proc2
,  TH1F *hb1  , string bkg_proc1 ,  TH1F *hb2  , string bkg_proc2 ,  TH1F *hb3  , string bkg_proc3 ){
using namespace std;
TStyle *gStyle = new TStyle("gStyle","Style for P-TDR");
setStyle st;
st.SetPars(gStyle);
char Variable[100];
char Cname[100];
const char *Var_Name;
Var_Name=VarName.c_str();
sprintf(Variable," ;%s; Events",Var_Name);
sprintf(Cname,"%s",Var_Name);
TPaveText *pCMS = new TPaveText(0.132107,0.9308003,0.8327759,0.9923583,"brNDC");
pCMS->SetBorderSize(0);
pCMS->SetFillStyle(0);
pCMS->SetTextAlign(11);
pCMS->SetTextFont(42);
pCMS->SetTextSize(0.04);
pCMS->AddText("CMS Phase 2 #it{Preliminary}                    ");
TLegend *leg=new TLegend(0.3582943,0.7051483,0.55025753,0.9049564,NULL,"brNDC");
leg->SetTextFont(62);
leg->SetLineColor(1);
leg->SetLineStyle(1);
leg->SetLineWidth(3);
leg->SetFillColor(0);
leg->SetFillStyle(1001);
leg->SetShadowColor(0);
leg->SetDrawOption(0);
leg->SetBorderSize(0);
leg->SetTextSize(0.03);
THStack *hallbkg=new THStack("hallbkg",Variable);
hb1->SetLineColor(1);
hallbkg->Add(hb1);
char h1L_bkg[100];
const char *h1_L_bkg;
h1_L_bkg=bkg_proc1.c_str();
sprintf(h1L_bkg,"%s",h1_L_bkg);
leg->AddEntry(hb1,h1L_bkg,"l");
hb2->SetLineColor(2);
hallbkg->Add(hb2);
char h2L_bkg[100];
const char *h2_L_bkg;
h2_L_bkg=bkg_proc2.c_str();
sprintf(h2L_bkg,"%s",h2_L_bkg);
leg->AddEntry(hb2,h2L_bkg,"l");
hb3->SetLineColor(3);
hallbkg->Add(hb3);
char h3L_bkg[100];
const char *h3_L_bkg;
h3_L_bkg=bkg_proc3.c_str();
sprintf(h3L_bkg,"%s",h3_L_bkg);
leg->AddEntry(hb3,h3L_bkg,"l");
hs1->SetFillStyle(1);
hs1->SetLineColor(11);
char h1L_sig[100];
const char *h1_L_sig;
h1_L_sig=sig_proc1.c_str();
sprintf(h1L_sig,"%s",h1_L_sig);
leg->AddEntry(hs1,h1L_sig,"l");
hs2->SetFillStyle(1);
hs2->SetLineColor(12);
char h2L_sig[100];
const char *h2_L_sig;
h2_L_sig=sig_proc2.c_str();
sprintf(h2L_sig,"%s",h2_L_sig);
leg->AddEntry(hs2,h2L_sig,"l");
TCanvas *c=new TCanvas(Cname,Cname);
c->cd();
hb1->Scale(1/hb1->Integral());
hb1->Draw("same");
hb2->Scale(1/hb2->Integral());
hb2->Draw("same");
hb3->Scale(1/hb3->Integral());
hb3->Draw("same");
hs1->Scale(1/hs1->Integral());
hs1->Draw("same");
hs2->Scale(1/hs2->Integral());
hs2->Draw("same");
txtGen->Draw();
pCMS->Draw();
leg->Draw();
c->Write();
}

void shapePlotter::plotS2B3D1( string VarName,TPaveText *txtGen , TH1F *hs1,  string sig_proc1, 
TH1F *hs2,  string sig_proc2, 
TH1F *hb1,  string bkg_proc1, 
TH1F *hb2,  string bkg_proc2, 
TH1F *hb3,  string bkg_proc3, 
TH1F *hd, string proc_data){
using namespace std;
TStyle *gStyle = new TStyle("gStyle","Style for P-TDR");
setStyle st;
st.SetPars(gStyle);
TPaveText *pCMS = new TPaveText(0.132107,0.9308003,0.8327759,0.9923583,"brNDC");
pCMS->SetBorderSize(0);
pCMS->SetFillStyle(0);
pCMS->SetTextAlign(11);
pCMS->SetTextFont(42);
pCMS->SetTextSize(0.04);
pCMS->AddText("CMS Phase 2 #it{Preliminary}                   ");
TLegend *leg=new TLegend(0.3582943,0.7051483,0.55025753,0.9049564,NULL,"brNDC");
leg->SetTextFont(62);
leg->SetLineColor(1);
leg->SetLineStyle(1);
leg->SetLineWidth(3);
leg->SetFillColor(0);
leg->SetFillStyle(1001);
leg->SetShadowColor(0);
leg->SetDrawOption(0);
leg->SetBorderSize(0);
leg->SetTextSize(0.03);
char Variable[100];
char Cname[100];
const char *Var_Name;
Var_Name=VarName.c_str();
sprintf(Variable," ;%s;Events",Var_Name);
sprintf(Cname,"%s",Var_Name);
THStack *hallbkg=new THStack("hallbkg",Variable);
hb1->SetLineColor(1);
hallbkg->Add(hb1);
char h1L_bkg[100];
const char *h1_L_bkg;
h1_L_bkg=bkg_proc1.c_str();
sprintf(h1L_bkg,"%s",h1_L_bkg);
leg->AddEntry(hb1,h1L_bkg,"l");
hb2->SetLineColor(2);
hallbkg->Add(hb2);
char h2L_bkg[100];
const char *h2_L_bkg;
h2_L_bkg=bkg_proc2.c_str();
sprintf(h2L_bkg,"%s",h2_L_bkg);
leg->AddEntry(hb2,h2L_bkg,"l");
hb3->SetLineColor(3);
hallbkg->Add(hb3);
char h3L_bkg[100];
const char *h3_L_bkg;
h3_L_bkg=bkg_proc3.c_str();
sprintf(h3L_bkg,"%s",h3_L_bkg);
leg->AddEntry(hb3,h3L_bkg,"l");
hs1->SetFillStyle(1);
hs1->SetLineColor(11);
char h1L_sig[100];
const char *h1_L_sig;
h1_L_sig=sig_proc1.c_str();
sprintf(h1L_sig,"%s",h1_L_sig);
leg->AddEntry(hs1,h1L_sig,"l");
hs2->SetFillStyle(1);
hs2->SetLineColor(12);
char h2L_sig[100];
const char *h2_L_sig;
h2_L_sig=sig_proc2.c_str();
sprintf(h2L_sig,"%s",h2_L_sig);
leg->AddEntry(hs2,h2L_sig,"l");
hd->SetLineColor(1);
hd->SetMarkerStyle(20);
char hL_data[100];
const char *h_L_data;
h_L_sig=proc_data.c_str();
sprintf(hL_data,"%s",h_L_sig);
leg->AddEntry(hd,hL_data,"p");
TCanvas *c=new TCanvas(Cname,Cname);
c->cd();
hb1->Scale(1/hb1->Integral());
hb1->Draw("same");
hb2->Scale(1/hb2->Integral());
hb2->Draw("same");
hb3->Scale(1/hb3->Integral());
hb3->Draw("same");
hs1->Scale(1/hs1->Integral());
hs1->Draw("same");
hs2->Scale(1/hs2->Integral());
hs2->Draw("same");
hd->Draw("P,E1 SAME");
txtGen->Draw();
pCMS->Draw();
leg->Draw();
c->Write();
}

void shapePlotter::plotS2B4D0( string VarName,TPaveText *txtGen , TH1F *hs1 , string sig_proc1
, TH1F *hs2 , string sig_proc2
,  TH1F *hb1  , string bkg_proc1 ,  TH1F *hb2  , string bkg_proc2 ,  TH1F *hb3  , string bkg_proc3 ,  TH1F *hb4  , string bkg_proc4 ){
using namespace std;
TStyle *gStyle = new TStyle("gStyle","Style for P-TDR");
setStyle st;
st.SetPars(gStyle);
char Variable[100];
char Cname[100];
const char *Var_Name;
Var_Name=VarName.c_str();
sprintf(Variable," ;%s; Events",Var_Name);
sprintf(Cname,"%s",Var_Name);
TPaveText *pCMS = new TPaveText(0.132107,0.9308003,0.8327759,0.9923583,"brNDC");
pCMS->SetBorderSize(0);
pCMS->SetFillStyle(0);
pCMS->SetTextAlign(11);
pCMS->SetTextFont(42);
pCMS->SetTextSize(0.04);
pCMS->AddText("CMS Phase 2 #it{Preliminary}                    ");
TLegend *leg=new TLegend(0.3582943,0.7051483,0.55025753,0.9049564,NULL,"brNDC");
leg->SetTextFont(62);
leg->SetLineColor(1);
leg->SetLineStyle(1);
leg->SetLineWidth(3);
leg->SetFillColor(0);
leg->SetFillStyle(1001);
leg->SetShadowColor(0);
leg->SetDrawOption(0);
leg->SetBorderSize(0);
leg->SetTextSize(0.03);
THStack *hallbkg=new THStack("hallbkg",Variable);
hb1->SetLineColor(1);
hallbkg->Add(hb1);
char h1L_bkg[100];
const char *h1_L_bkg;
h1_L_bkg=bkg_proc1.c_str();
sprintf(h1L_bkg,"%s",h1_L_bkg);
leg->AddEntry(hb1,h1L_bkg,"l");
hb2->SetLineColor(2);
hallbkg->Add(hb2);
char h2L_bkg[100];
const char *h2_L_bkg;
h2_L_bkg=bkg_proc2.c_str();
sprintf(h2L_bkg,"%s",h2_L_bkg);
leg->AddEntry(hb2,h2L_bkg,"l");
hb3->SetLineColor(3);
hallbkg->Add(hb3);
char h3L_bkg[100];
const char *h3_L_bkg;
h3_L_bkg=bkg_proc3.c_str();
sprintf(h3L_bkg,"%s",h3_L_bkg);
leg->AddEntry(hb3,h3L_bkg,"l");
hb4->SetLineColor(4);
hallbkg->Add(hb4);
char h4L_bkg[100];
const char *h4_L_bkg;
h4_L_bkg=bkg_proc4.c_str();
sprintf(h4L_bkg,"%s",h4_L_bkg);
leg->AddEntry(hb4,h4L_bkg,"l");
hs1->SetFillStyle(1);
hs1->SetLineColor(11);
char h1L_sig[100];
const char *h1_L_sig;
h1_L_sig=sig_proc1.c_str();
sprintf(h1L_sig,"%s",h1_L_sig);
leg->AddEntry(hs1,h1L_sig,"l");
hs2->SetFillStyle(1);
hs2->SetLineColor(12);
char h2L_sig[100];
const char *h2_L_sig;
h2_L_sig=sig_proc2.c_str();
sprintf(h2L_sig,"%s",h2_L_sig);
leg->AddEntry(hs2,h2L_sig,"l");
TCanvas *c=new TCanvas(Cname,Cname);
c->cd();
hb1->Scale(1/hb1->Integral());
hb1->Draw("same");
hb2->Scale(1/hb2->Integral());
hb2->Draw("same");
hb3->Scale(1/hb3->Integral());
hb3->Draw("same");
hb4->Scale(1/hb4->Integral());
hb4->Draw("same");
hs1->Scale(1/hs1->Integral());
hs1->Draw("same");
hs2->Scale(1/hs2->Integral());
hs2->Draw("same");
txtGen->Draw();
pCMS->Draw();
leg->Draw();
c->Write();
}

void shapePlotter::plotS2B4D1( string VarName,TPaveText *txtGen , TH1F *hs1,  string sig_proc1, 
TH1F *hs2,  string sig_proc2, 
TH1F *hb1,  string bkg_proc1, 
TH1F *hb2,  string bkg_proc2, 
TH1F *hb3,  string bkg_proc3, 
TH1F *hb4,  string bkg_proc4, 
TH1F *hd, string proc_data){
using namespace std;
TStyle *gStyle = new TStyle("gStyle","Style for P-TDR");
setStyle st;
st.SetPars(gStyle);
TPaveText *pCMS = new TPaveText(0.132107,0.9308003,0.8327759,0.9923583,"brNDC");
pCMS->SetBorderSize(0);
pCMS->SetFillStyle(0);
pCMS->SetTextAlign(11);
pCMS->SetTextFont(42);
pCMS->SetTextSize(0.04);
pCMS->AddText("CMS Phase 2 #it{Preliminary}                   ");
TLegend *leg=new TLegend(0.3582943,0.7051483,0.55025753,0.9049564,NULL,"brNDC");
leg->SetTextFont(62);
leg->SetLineColor(1);
leg->SetLineStyle(1);
leg->SetLineWidth(3);
leg->SetFillColor(0);
leg->SetFillStyle(1001);
leg->SetShadowColor(0);
leg->SetDrawOption(0);
leg->SetBorderSize(0);
leg->SetTextSize(0.03);
char Variable[100];
char Cname[100];
const char *Var_Name;
Var_Name=VarName.c_str();
sprintf(Variable," ;%s;Events",Var_Name);
sprintf(Cname,"%s",Var_Name);
THStack *hallbkg=new THStack("hallbkg",Variable);
hb1->SetLineColor(1);
hallbkg->Add(hb1);
char h1L_bkg[100];
const char *h1_L_bkg;
h1_L_bkg=bkg_proc1.c_str();
sprintf(h1L_bkg,"%s",h1_L_bkg);
leg->AddEntry(hb1,h1L_bkg,"l");
hb2->SetLineColor(2);
hallbkg->Add(hb2);
char h2L_bkg[100];
const char *h2_L_bkg;
h2_L_bkg=bkg_proc2.c_str();
sprintf(h2L_bkg,"%s",h2_L_bkg);
leg->AddEntry(hb2,h2L_bkg,"l");
hb3->SetLineColor(3);
hallbkg->Add(hb3);
char h3L_bkg[100];
const char *h3_L_bkg;
h3_L_bkg=bkg_proc3.c_str();
sprintf(h3L_bkg,"%s",h3_L_bkg);
leg->AddEntry(hb3,h3L_bkg,"l");
hb4->SetLineColor(4);
hallbkg->Add(hb4);
char h4L_bkg[100];
const char *h4_L_bkg;
h4_L_bkg=bkg_proc4.c_str();
sprintf(h4L_bkg,"%s",h4_L_bkg);
leg->AddEntry(hb4,h4L_bkg,"l");
hs1->SetFillStyle(1);
hs1->SetLineColor(11);
char h1L_sig[100];
const char *h1_L_sig;
h1_L_sig=sig_proc1.c_str();
sprintf(h1L_sig,"%s",h1_L_sig);
leg->AddEntry(hs1,h1L_sig,"l");
hs2->SetFillStyle(1);
hs2->SetLineColor(12);
char h2L_sig[100];
const char *h2_L_sig;
h2_L_sig=sig_proc2.c_str();
sprintf(h2L_sig,"%s",h2_L_sig);
leg->AddEntry(hs2,h2L_sig,"l");
hd->SetLineColor(1);
hd->SetMarkerStyle(20);
char hL_data[100];
const char *h_L_data;
h_L_sig=proc_data.c_str();
sprintf(hL_data,"%s",h_L_sig);
leg->AddEntry(hd,hL_data,"p");
TCanvas *c=new TCanvas(Cname,Cname);
c->cd();
hb1->Scale(1/hb1->Integral());
hb1->Draw("same");
hb2->Scale(1/hb2->Integral());
hb2->Draw("same");
hb3->Scale(1/hb3->Integral());
hb3->Draw("same");
hb4->Scale(1/hb4->Integral());
hb4->Draw("same");
hs1->Scale(1/hs1->Integral());
hs1->Draw("same");
hs2->Scale(1/hs2->Integral());
hs2->Draw("same");
hd->Draw("P,E1 SAME");
txtGen->Draw();
pCMS->Draw();
leg->Draw();
c->Write();
}

